use serde::Deserialize;
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::io::{Cursor, Read};
use std::path::PathBuf;
use zip::ZipArchive;

type BuildResult<T> = Result<T, Box<dyn Error>>;

#[derive(Debug, Deserialize)]
struct SourceVec3 {
    #[serde(rename = "X")]
    x: f64,
    #[serde(rename = "Y")]
    y: f64,
    #[serde(rename = "Z")]
    z: f64,
}

#[derive(Debug, Deserialize)]
struct SourceBounds {
    #[serde(rename = "Minimum")]
    min: SourceVec3,
    #[serde(rename = "Maximum")]
    max: SourceVec3,
}

#[derive(Debug, Deserialize)]
struct SourceZone {
    #[serde(rename = "Name")]
    name: String,
    #[serde(rename = "DisplayName")]
    display_name: Option<String>,
    #[serde(rename = "Bounds")]
    bounds: Vec<SourceBounds>,
}

#[derive(Debug, Deserialize)]
struct SourceNodeCell {
    #[serde(rename = "AreaId")]
    area_id: u16,
    #[serde(rename = "Nodes")]
    nodes: Vec<SourceNode>,
}

#[derive(Debug, Deserialize)]
struct SourceNode {
    #[serde(rename = "Id")]
    id: u16,
    #[serde(rename = "StreetName")]
    street_name: String,
    #[serde(rename = "Position")]
    position: SourceVec3,
    #[serde(rename = "ConnectedNodes")]
    connected_nodes: Option<Vec<SourceConnectedNode>>,
}

#[derive(Debug, Deserialize)]
struct SourceConnectedNode {
    #[serde(rename = "Node")]
    node: SourceNode,
}

#[derive(Debug)]
struct SourceRoadSegment {
    street_name: String,
    start_area_id: u16,
    start_node_id: u16,
    end_node_id: u16,
    start: SourceVec3,
    end: SourceVec3,
}

fn main() -> BuildResult<()> {
    println!("cargo:rerun-if-changed=data/zones.json");
    println!("cargo:rerun-if-changed=data/nodes.zip");

    let zones = read_zones()?;
    let road_segments = read_road_segments()?;

    if zones.is_empty() {
        return Err("data/zones.json did not contain any zones".into());
    }

    if road_segments.is_empty() {
        return Err("data/nodes.zip did not contain any named road segments".into());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    fs::write(
        out_dir.join("generated_data.rs"),
        render_generated_data(&zones, &road_segments)?,
    )?;

    Ok(())
}

fn read_zones() -> BuildResult<Vec<SourceZone>> {
    let zones_json = fs::read_to_string("data/zones.json")?;
    Ok(serde_json::from_str(&zones_json)?)
}

fn read_road_segments() -> BuildResult<Vec<SourceRoadSegment>> {
    let nodes_zip = fs::read("data/nodes.zip")?;
    let cursor = Cursor::new(nodes_zip);
    let mut archive = ZipArchive::new(cursor)?;
    let mut nodes_json = String::new();

    archive
        .by_name("nodes.json")?
        .read_to_string(&mut nodes_json)?;

    let cells: Vec<SourceNodeCell> = serde_json::from_str(&nodes_json)?;
    let mut segments = Vec::new();

    for cell in cells {
        for node in cell.nodes {
            let Some(connected_nodes) = node.connected_nodes.as_ref() else {
                continue;
            };

            for connected in connected_nodes {
                let street_name = pick_street_name(&node.street_name, &connected.node.street_name);
                if street_name.is_empty() {
                    continue;
                }

                segments.push(SourceRoadSegment {
                    street_name: street_name.to_string(),
                    start_area_id: cell.area_id,
                    start_node_id: node.id,
                    end_node_id: connected.node.id,
                    start: SourceVec3 {
                        x: node.position.x,
                        y: node.position.y,
                        z: node.position.z,
                    },
                    end: SourceVec3 {
                        x: connected.node.position.x,
                        y: connected.node.position.y,
                        z: connected.node.position.z,
                    },
                });
            }
        }
    }

    Ok(segments)
}

fn pick_street_name<'a>(first: &'a str, second: &'a str) -> &'a str {
    if is_real_street_name(first) {
        first
    } else if is_real_street_name(second) {
        second
    } else {
        ""
    }
}

fn is_real_street_name(name: &str) -> bool {
    let trimmed = name.trim();
    !trimmed.is_empty() && trimmed != "0"
}

fn render_generated_data(
    zones: &[SourceZone],
    road_segments: &[SourceRoadSegment],
) -> BuildResult<String> {
    let mut output = String::new();

    output.push_str("// @generated by build.rs; do not edit by hand.\n");
    output.push_str("use super::{Bounds, RoadSegment, Vec3, Zone};\n\n");

    for (index, zone) in zones.iter().enumerate() {
        writeln!(output, "static ZONE_{index}_BOUNDS: &[Bounds] = &[")?;
        for bounds in &zone.bounds {
            writeln!(
                output,
                "    Bounds {{ min: {}, max: {} }},",
                rust_vec3(&bounds.min)?,
                rust_vec3(&bounds.max)?
            )?;
        }
        output.push_str("];\n\n");
    }

    output.push_str("pub static ZONES: &[Zone] = &[\n");
    for (index, zone) in zones.iter().enumerate() {
        writeln!(
            output,
            "    Zone {{ name: {}, display_name: {}, bounds: ZONE_{index}_BOUNDS }},",
            rust_string(&zone.name),
            rust_optional_string(zone.display_name.as_deref())
        )?;
    }
    output.push_str("];\n\n");

    output.push_str("pub static ROAD_SEGMENTS: &[RoadSegment] = &[\n");
    for segment in road_segments {
        writeln!(
            output,
            "    RoadSegment {{ street_name: {}, start_area_id: {}, start_node_id: {}, end_node_id: {}, start: {}, end: {} }},",
            rust_string(&segment.street_name),
            segment.start_area_id,
            segment.start_node_id,
            segment.end_node_id,
            rust_vec3(&segment.start)?,
            rust_vec3(&segment.end)?
        )?;
    }
    output.push_str("];\n");

    Ok(output)
}

fn rust_vec3(vec: &SourceVec3) -> BuildResult<String> {
    Ok(format!(
        "Vec3 {{ x: {}, y: {}, z: {} }}",
        rust_float(vec.x)?,
        rust_float(vec.y)?,
        rust_float(vec.z)?
    ))
}

fn rust_float(value: f64) -> BuildResult<String> {
    if !value.is_finite() {
        return Err(format!("cannot generate Rust literal for non-finite float: {value}").into());
    }

    Ok(format!("{value:?}"))
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn rust_optional_string(value: Option<&str>) -> String {
    match value {
        Some(value) => format!("Some({})", rust_string(value)),
        None => "None".to_string(),
    }
}
